spring:
  application:
    name: hexa-task
  data:
    mongodb:
      database: hexa-task
      uri: ${MONGODB_URI}
    redis:
      host: localhost
      port: 6379
      database: 1
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
        mail:
            smtp:
              auth: true
              starttls:
                enable: true
server:
  servlet:
    context-path: /hexa-task/api/v1
  port: ${SERVER_PORT}

application:
  email:
    token-expiration: 10800000
  security:
    jwt:
      tokenHeader: Authorization
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 30000
      refresh-token:
        expiration: 120000